-- Execute este arquivo no SQL Editor do Supabase.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('site-media', 'site-media', true, 26214400, array['image/*', 'video/*'])
on conflict (id) do update set public = true, file_size_limit = 26214400, allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Administradores podem enviar midia" on storage.objects;
create policy "Administradores podem enviar midia" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'site-media');

drop policy if exists "Publico pode visualizar midia do site" on storage.objects;
create policy "Publico pode visualizar midia do site" on storage.objects
  for select to public
  using (bucket_id = 'site-media');

create table if not exists public.solicitacoes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  telefone text not null,
  email text not null,
  servico text not null,
  mensagem text,
  status text not null default 'pendente' check (status in ('pendente', 'atendido'))
);

alter table public.solicitacoes enable row level security;

revoke all on table public.solicitacoes from anon, authenticated;
grant insert on table public.solicitacoes to anon;
grant select, update, delete on table public.solicitacoes to authenticated;
grant usage, select on sequence public.solicitacoes_id_seq to anon, authenticated;

drop policy if exists "Publico pode enviar solicitacoes" on public.solicitacoes;
create policy "Publico pode enviar solicitacoes"
  on public.solicitacoes for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Administradores podem visualizar solicitacoes" on public.solicitacoes;
create policy "Administradores podem visualizar solicitacoes"
  on public.solicitacoes for select
  to authenticated
  using (true);

drop policy if exists "Administradores podem atualizar solicitacoes" on public.solicitacoes;
create policy "Administradores podem atualizar solicitacoes"
  on public.solicitacoes for update
  to authenticated
  using (true)
  with check (status in ('pendente', 'atendido'));

drop policy if exists "Administradores podem excluir solicitacoes" on public.solicitacoes;
create policy "Administradores podem excluir solicitacoes"
  on public.solicitacoes for delete
  to authenticated
  using (true);

create index if not exists solicitacoes_created_at_idx on public.solicitacoes (created_at desc);

-- Conteúdo editável pelo painel administrativo.
create table if not exists public.site_content (
  id text primary key default 'principal' check (id = 'principal'),
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  icon text not null default 'icon-wall',
  image_url text not null default '',
  media_type text not null default 'image',
  sort_order integer not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'outro',
  type_label text not null default '',
  location text not null default '',
  image_url text not null default '',
  media_type text not null default 'image',
  sort_order integer not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.services add column if not exists media_type text not null default 'image';
alter table public.projects add column if not exists media_type text not null default 'image';

alter table public.site_content enable row level security;
alter table public.services enable row level security;
alter table public.projects enable row level security;

revoke all on table public.site_content, public.services, public.projects from anon, authenticated;
grant select on table public.site_content, public.services, public.projects to anon, authenticated;
grant insert, update, delete on table public.site_content, public.services, public.projects to authenticated;
grant usage, select on sequence public.services_id_seq, public.projects_id_seq to authenticated;

drop policy if exists "Publico pode ler conteudo do site" on public.site_content;
create policy "Publico pode ler conteudo do site" on public.site_content for select to anon, authenticated using (true);
drop policy if exists "Administrador gerencia conteudo do site" on public.site_content;
create policy "Administrador gerencia conteudo do site" on public.site_content for all to authenticated using (true) with check (true);

drop policy if exists "Publico pode ler servicos ativos" on public.services;
create policy "Publico pode ler servicos ativos" on public.services for select to anon, authenticated using (active = true or auth.role() = 'authenticated');
drop policy if exists "Administrador gerencia servicos" on public.services;
create policy "Administrador gerencia servicos" on public.services for all to authenticated using (true) with check (true);

drop policy if exists "Publico pode ler obras ativas" on public.projects;
create policy "Publico pode ler obras ativas" on public.projects for select to anon, authenticated using (active = true or auth.role() = 'authenticated');
drop policy if exists "Administrador gerencia obras" on public.projects;
create policy "Administrador gerencia obras" on public.projects for all to authenticated using (true) with check (true);

create index if not exists services_sort_order_idx on public.services (sort_order);
create index if not exists projects_sort_order_idx on public.projects (sort_order);

insert into public.site_content (id, content)
values ('principal', jsonb_build_object(
  'hero_title', 'Soluções em engenharia e construção para obras que precisam de resistência.',
  'hero_text', 'Atuamos com gabiões, estruturas metálicas, terraplenagem, drenagem e infraestrutura, entregando segurança, qualidade e resultados para o seu projeto.',
  'hero_image', 'assets/images/Gabion_retaining_project_in_Brazil_2K_20260913135240.jpeg',
  'services_title', 'Nossas soluções',
  'about_title', 'Mais que obras, entregamos soluções.',
  'about_text', 'A WM Gabião atua no segmento de engenharia e construção com foco em soluções de contenção, drenagem, terraplenagem, estruturas metálicas e infraestrutura. Ativa desde 23/05/2023, somos uma microempresa com atuação em todo o Brasil. Nosso compromisso é transformar projetos em resultados concretos, com qualidade, segurança e responsabilidade.',
  'about_image', 'assets/images/Engineering_team_at_construction%E2%80%A6_2K_20260913135158.jpeg',
  'budget_title', 'Vamos conversar sobre seu projeto?',
  'budget_text', 'Preencha o formulário e nossa equipe entrará em contato para entender sua necessidade e avaliar a melhor solução.',
  'budget_image', 'assets/images/Infrastructure_construction_proj%E2%80%A6_2K_20260913135230.jpeg',
  'footer_text', 'Soluções em engenharia e construção para obras que precisam de resistência.',
  'phone', '(15) 99116-7340', 'email', 'eduatdo.oliveira222220@gmail.com', 'location', 'Atendimento em todo o Brasil', 'hours', '24 horas',
  'whatsapp', '5515991167340', 'instagram', 'wmgabiao', 'stats_works', '25', 'stats_projects', '25', 'stats_people', '6', 'stats_area', 'Brasil inteiro'
))
on conflict (id) do nothing;

insert into public.services (title, description, icon, sort_order)
select item.title, item.description, item.icon, item.sort_order
from (values
  ('Contenção e estabilização', 'Gabiões, muros de contenção e soluções para encostas e taludes.', 'icon-wall', 1),
  ('Drenagem e controle de erosão', 'Sistemas de drenagem e proteção de margens.', 'icon-drain', 2),
  ('Terraplenagem', 'Movimentação de solo e preparação do terreno.', 'icon-excavator', 3),
  ('Estruturas metálicas', 'Projetos e montagens de estruturas metálicas.', 'icon-steel', 4),
  ('Infraestrutura', 'Obras urbanas, vias, praças e demais soluções de infraestrutura.', 'icon-road', 5)
) as item(title, description, icon, sort_order)
where not exists (select 1 from public.services);

-- Mantém as imagens locais do site também para registros já existentes.
update public.services set image_url = case title
  when 'Contenção e estabilização' then 'assets/images/Gabion_retaining_wall_stabilizin%E2%80%A6_2K_20260913135247.jpeg'
  when 'Drenagem e controle de erosão' then 'assets/images/Gabion_drainage_erosion_control_%E2%80%A6_2K_20260913135256.jpeg'
  when 'Terraplenagem' then 'assets/images/Infrastructure_construction_proj%E2%80%A6_2K_20260913135230.jpeg'
  when 'Estruturas metálicas' then 'assets/images/Gabion_structure_with_stones_2K_20260913135215.jpeg'
  when 'Infraestrutura' then 'assets/images/images%20(2).jpeg'
  else image_url
end
where title in ('Contenção e estabilização', 'Drenagem e controle de erosão', 'Terraplenagem', 'Estruturas metálicas', 'Infraestrutura')
  and coalesce(image_url, '') = '';

insert into public.projects (title, category, type_label, location, sort_order)
select item.title, item.category, item.type_label, item.location, item.sort_order
from (values
  ('Projeto de contenção de margem', 'contencao', 'Contenção de margem', 'Brasil', 1),
  ('Estrutura metálica industrial', 'estrutura', 'Estrutura metálica', 'Brasil', 2),
  ('Preparação e nivelamento de terreno', 'terraplenagem', 'Terraplenagem', 'Brasil', 3),
  ('Drenagem e controle de erosão', 'drenagem', 'Drenagem', 'Brasil', 4),
  ('Infraestrutura urbana', 'urbana', 'Obras urbanas', 'Brasil', 5)
) as item(title, category, type_label, location, sort_order)
where not exists (select 1 from public.projects);

update public.projects set image_url = case title
  when 'Projeto de contenção de margem' then 'assets/images/Gabion_retaining_project_in_Brazil_2K_20260913135240.jpeg'
  when 'Estrutura metálica industrial' then 'assets/images/Engineering_team_at_construction%E2%80%A6_2K_20260913135158.jpeg'
  when 'Preparação e nivelamento de terreno' then 'assets/images/Infrastructure_construction_proj%E2%80%A6_2K_20260913135230.jpeg'
  when 'Drenagem e controle de erosão' then 'assets/images/Gabion_drainage_erosion_control_%E2%80%A6_2K_20260913135256.jpeg'
  when 'Infraestrutura urbana' then 'assets/images/images%20(1).jpeg'
  else image_url
end
where title in ('Projeto de contenção de margem', 'Estrutura metálica industrial', 'Preparação e nivelamento de terreno', 'Drenagem e controle de erosão', 'Infraestrutura urbana')
  and coalesce(image_url, '') = '';
