-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.solicitacoes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  telefone text not null,
  email text not null,
  servico text not null,
  mensagem text,
  status text not null default 'pendente' check (status in ('pendente', 'atendido'))
);

alter table public.solicitacoes enable row level security;

revoke all on table public.solicitacoes from anon, authenticated;
grant insert on table public.solicitacoes to anon;
grant select, update, delete on table public.solicitacoes to authenticated;
grant usage, select on sequence public.solicitacoes_id_seq to anon, authenticated;

drop policy if exists "Publico pode enviar solicitacoes" on public.solicitacoes;
create policy "Publico pode enviar solicitacoes"
  on public.solicitacoes for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Administradores podem visualizar solicitacoes" on public.solicitacoes;
create policy "Administradores podem visualizar solicitacoes"
  on public.solicitacoes for select
  to authenticated
  using (true);

drop policy if exists "Administradores podem atualizar solicitacoes" on public.solicitacoes;
create policy "Administradores podem atualizar solicitacoes"
  on public.solicitacoes for update
  to authenticated
  using (true)
  with check (status in ('pendente', 'atendido'));

drop policy if exists "Administradores podem excluir solicitacoes" on public.solicitacoes;
create policy "Administradores podem excluir solicitacoes"
  on public.solicitacoes for delete
  to authenticated
  using (true);

create index if not exists solicitacoes_created_at_idx on public.solicitacoes (created_at desc);
